---

- name: stop and disable (systemd-resolved) service
  service:
    name: systemd-resolved
    state: stopped
    enabled: false
  when:
    - dnsmasq_resolved_disabled | bool
  tags:
    - configuration
    - dnsmasq
    - dnsmasq-stop-disable-service

- name: restart dnsmasq if needed
  meta: flush_handlers

- name: ensure dnsmasq is enabled on boot
  become: true
  service:
    name: dnsmasq
    enabled: true
    state: started

...
